//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::product::Entity as Product;
pub use super::shopping_cart::Entity as ShoppingCart;
pub use super::shopping_cart_product::Entity as ShoppingCartProduct;
