//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use rocket::serde::Serialize;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[serde(crate = "rocket::serde")]
#[sea_orm(table_name = "product")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub value: Decimal,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::shopping_cart_product::Entity")]
    ShoppingCartProduct,
}

impl Related<super::shopping_cart_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShoppingCartProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
