//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "shopping_cart")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_type = "Decimal(Some((15, 2)))")]
    pub value: Decimal,
    pub tax_id: String,
    pub status: String,
    pub created_at: DateTime,
    pub updated_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::shopping_cart_product::Entity")]
    ShoppingCartProduct,
}

impl Related<super::shopping_cart_product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ShoppingCartProduct.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
